name = "raspberry_bsp"
description = "Board Support package for Raspberry PI v1, v2 and B+"
version = "1.0.0"

authors = ["Tama McGlinn"]
maintainers = ["Tama McGlinn <t.mcglinn@gmail.com>"]
maintainers-logins = ["TamaMcGlinn"]
